#!/usr/bin/env bash
# bench-history.sh — run every Cyrius benchmark, append to bench-history.csv,
# and regenerate the human-readable table in BENCHMARKS.md.
#
# first-party-standards.md:443-447 gives this script a four-clause contract:
#
#   - Run `cyrius bench`, capture output
#   - Parse the time format, normalize all units to nanoseconds
#   - Append to CSV with timestamp, commit hash, branch
#   - Generate a Markdown table with human-readable units
#
# ⚠ The commit/branch columns and the Markdown half are the two clauses the
# sibling implementations drop — agnosai's script writes only
# date,version,benchmark,time_ns and emits no table. Without the commit hash a
# row cannot be attributed to code, which defeats the whole point of a history
# trail; without the table nobody reads the CSV.
#
# Output line shape this parses (lib/bench.cyr `bench_report`):
#   "  noop: 2ns avg (min=2ns max=2ns) [1000000 iters]"
#
# ⚠ The pattern is anchored on the "<value><unit> avg" shape deliberately.
# `cyrius bench` shares its stream with build notes, unreachable-fn counts,
# timer-floor lines and duplicate-fn warnings from lib/; an unanchored grep
# picks those up as benchmarks.
set -euo pipefail

CSV="bench-history.csv"
MD="BENCHMARKS.md"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
VERSION="$(tr -d '[:space:]' < VERSION 2>/dev/null || echo unknown)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo nogit)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo nogit)"

# `git describe --dirty` would be nicer but a dirty tree is the normal state
# while benchmarking a change, so record it as a flag rather than refusing.
DIRTY=""
if ! git diff --quiet 2>/dev/null; then DIRTY=" (dirty)"; fi

if [ ! -f "$CSV" ]; then
    echo "date,version,commit,branch,benchmark,time_ns" > "$CSV"
fi

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

echo "Running benchmarks at ${COMMIT}${DIRTY} on ${BRANCH}..."
cyrius bench 2>&1 | tee "$TMPFILE"

ROWS=0
while IFS= read -r line; do
    name=$(sed -E 's/^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*):.*/\1/' <<<"$line")
    value=$(sed -E 's/^[^:]*:[[:space:]]*([0-9.]+)(ns|us|ms|s) avg.*/\1/' <<<"$line")
    unit=$(sed -E 's/^[^:]*:[[:space:]]*([0-9.]+)(ns|us|ms|s) avg.*/\2/' <<<"$line")

    # Normalise to nanoseconds. ERE alternation is leftmost-longest, so
    # "ns"/"us"/"ms" always win over the bare "s" branch.
    case "$unit" in
        ns) scale=1 ;;
        us) scale=1000 ;;
        ms) scale=1000000 ;;
        s)  scale=1000000000 ;;
        *)  continue ;;
    esac
    ns=$(awk -v v="$value" -v s="$scale" 'BEGIN { printf "%.0f", v * s }')

    if [ -n "$name" ] && [ "$ns" != "0" ]; then
        echo "${DATE},${VERSION},${COMMIT},${BRANCH},${name},${ns}" >> "$CSV"
        ROWS=$((ROWS + 1))
    fi
done < <(grep -E '^[[:space:]]+[A-Za-z_][A-Za-z0-9_]*: [0-9.]+(ns|us|ms|s) avg' "$TMPFILE" || true)

if [ "$ROWS" -eq 0 ]; then
    echo "No benchmark results parsed — nothing appended."
    echo "  (if benches exist, check that bench_report output still matches the"
    echo "   '<name>: <value><unit> avg' shape this script anchors on)"
    exit 0
fi

echo "Appended $ROWS benchmark entries to $CSV"

# --- Markdown half: latest run per benchmark, human-readable ---------------
# Reads the CSV back rather than the captured output so the table always
# reflects what was actually recorded.
{
    echo "# Benchmarks"
    echo
    echo "Generated by \`./scripts/bench-history.sh\` — do not edit by hand."
    echo "Full history, one row per run, is in [\`bench-history.csv\`](bench-history.csv)."
    echo
    echo "**Latest:** \`${COMMIT}\`${DIRTY} on \`${BRANCH}\`, version ${VERSION}, ${DATE}"
    echo
    echo "| Benchmark | Time | Runs recorded | First seen |"
    echo "|-----------|-----:|--------------:|------------|"
    awk -F, 'NR > 1 {
        count[$5]++
        if (!($5 in first)) first[$5] = $1
        # CSV is append-only and chronological, so the last row wins.
        latest[$5] = $6
        order[$5] = NR
    }
    END {
        for (b in latest) {
            ns = latest[b] + 0
            if (ns < 1000)            { printf "| `%s` | %d ns | %d | %s |\n", b, ns, count[b], substr(first[b],1,10) }
            else if (ns < 1000000)    { printf "| `%s` | %.3f µs | %d | %s |\n", b, ns/1000, count[b], substr(first[b],1,10) }
            else if (ns < 1000000000) { printf "| `%s` | %.3f ms | %d | %s |\n", b, ns/1000000, count[b], substr(first[b],1,10) }
            else                      { printf "| `%s` | %.3f s | %d | %s |\n",  b, ns/1000000000, count[b], substr(first[b],1,10) }
        }
    }' "$CSV" | sort
    echo
    echo "## Reading these numbers"
    echo
    echo "\`cyrius bench\` measures and subtracts the clock-read floor (printed as"
    echo "\`timer floor N per clock read\`) from every sample, so a sub-100ns figure"
    echo "is a real measurement rather than timer noise. Batch anything below ~1µs"
    echo "with \`bench_batch_start\`/\`bench_batch_stop\` and an iteration count of"
    echo "1000+ to amortise that floor."
    echo
    echo "Rows are **not** comparable against the Python oracle in \`python-port/\`."
    echo "Different runtime, allocator, harness and statistics; the Cyrius line"
    echo "starts its own baseline. See \`ORACLE-AUDIT.md\` §4 for why the oracle's"
    echo "own published benchmark numbers should not be used as a target either."
} > "$MD"

echo "Regenerated $MD"
